### Frobenius Norm 

In [1]:
import numpy as np
import torch as pt
import tensorflow as tf

In [2]:
X = np.array ([[2,3,4],[5,4,6]])
X

array([[2, 3, 4],
       [5, 4, 6]])

In [3]:
frobenius_norm = (2**2 + 3**2 + 4**2 + 5**2 + 4**2 + 6**2)**(1/2)
frobenius_norm 

10.295630140987

In [4]:
np.linalg.norm(X)

10.295630140987

In [5]:
X_pt = pt.tensor([[2,3,4],[5,4,6.]])  # torch norm requires flot type (6.)
X_pt

tensor([[2., 3., 4.],
        [5., 4., 6.]])

In [6]:
pt.norm(X_pt)

tensor(10.2956)

In [7]:
X_tf = tf.Variable([[2,3,4],[5,4,6.]])  # torch norm requires flot type (6.)
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 4., 6.]], dtype=float32)>

In [8]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=10.29563>

### Matrix maltiplication (with vectors ) 

In [9]:
A = np.array([[5,6,7],[2,4,5]])
A

array([[5, 6, 7],
       [2, 4, 5]])

In [10]:
b = np.array([2,6,8])
b

array([2, 6, 8])

In [11]:
np.dot(A,b)  # even though technicallt dot product only between vectors 

array([102,  68])

In [12]:
A_tf = tf.Variable([[5,6,7],[2,4,5]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[5, 6, 7],
       [2, 4, 5]])>

In [13]:
b_tf = tf.Variable([2,6,8])
b_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 6, 8])>

In [14]:
tf.linalg.matvec(A_tf,b_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([102,  68])>

In [15]:
A_pt = pt.tensor([[5,6,7],[2,4,5]])
A_pt

tensor([[5, 6, 7],
        [2, 4, 5]])

In [16]:
b_pt = pt.tensor([2,6,8])
b_pt

tensor([2, 6, 8])

In [17]:
pt.matmul(A_pt,b_pt)

tensor([102,  68])

### Matrix maltiplication (with metrix ) 

In [18]:
A = np.array ([[2,3,4],[3,5,6]])
A

array([[2, 3, 4],
       [3, 5, 6]])

In [19]:
B = np.array ([[4,5],[4,6],[3,4]])
B

array([[4, 5],
       [4, 6],
       [3, 4]])

In [20]:
np.dot(A,B)

array([[32, 44],
       [50, 69]])

In [21]:
np.dot(B,A)  # in matrix maltiplication AB != BA 

array([[23, 37, 46],
       [26, 42, 52],
       [18, 29, 36]])

In [22]:
A_pt = pt.from_numpy(A)
A_pt

tensor([[2, 3, 4],
        [3, 5, 6]], dtype=torch.int32)

In [23]:
B_pt = pt.from_numpy(B)
B_pt

tensor([[4, 5],
        [4, 6],
        [3, 4]], dtype=torch.int32)

In [24]:
pt.matmul(A_pt,B_pt)

tensor([[32, 44],
        [50, 69]], dtype=torch.int32)

In [25]:
A_tf = tf.convert_to_tensor(A)
A_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 5, 6]])>

In [26]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [4, 6],
       [3, 4]])>

In [27]:
tf.matmul(A_tf,B_tf)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 44],
       [50, 69]])>

### symmetric Matrices  

In [28]:
A = np.array([[2,3,4],[3,5,7],[4,7,9]])
A

array([[2, 3, 4],
       [3, 5, 7],
       [4, 7, 9]])

In [29]:
A_T = A.T
A_T 

array([[2, 3, 4],
       [3, 5, 7],
       [4, 7, 9]])

In [30]:
A == A_T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Identity Matrix 

In [31]:
I = tf.Variable ([[1,0,0],[0,1,0],[0,0,1]])
I 

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>

In [32]:
a = tf.Variable([2,3,4])
a

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4])>

In [33]:
tf.linalg.matvec(I,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

###### Questions answer

In [34]:
A = np.array([[0,1,2],[3,4,5],[6,7,8]])
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
b = np.array([[-1],[1],[-2]])
b

array([[-1],
       [ 1],
       [-2]])

In [36]:
np.dot(A,b)

array([[ -3],
       [ -9],
       [-15]])

In [37]:
A_pt = pt.from_numpy(A)
A_pt

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)

In [38]:
B_pt = pt.from_numpy(b)
B_pt

tensor([[-1],
        [ 1],
        [-2]], dtype=torch.int32)

In [39]:
pt.matmul(A_pt,B_pt)

tensor([[ -3],
        [ -9],
        [-15]], dtype=torch.int32)

In [40]:
I_pt = pt.tensor([[1,0,0],[0,1,0],[0,0,1]])
I_pt

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [41]:
B_pt = pt.tensor([[1],[3],[4]])
B_pt

tensor([[1],
        [3],
        [4]])

In [42]:
pt.matmul(I_pt,B_pt)

tensor([[1],
        [3],
        [4]])

In [43]:
E = np.array([[0,1,2],[3,4,5],[6,7,8]])
E

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
F = np.array([[-1,0],[1,1],[-2,2]])
F

array([[-1,  0],
       [ 1,  1],
       [-2,  2]])

In [45]:
np.matmul(E,F)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])

### Matrix Inversion 

     find a,b
       4a + 2b = 4
      -5a - 3b = -7
     
     [[4,2],[-5,-3]] * [a,b] = [4,-7]
             X       *   w   =    y
      X*w = y 
      w = X**(-1) * y  ##  X**(-1) = Xinv
      w = Xinv * y
        = [a,b]

In [46]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [47]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [48]:
y = np.array([4,-7])
y

array([ 4, -7])

In [49]:
w = np.dot(Xinv,y)
w

array([-1.,  4.])

    to Show that y = Xw

In [50]:
np.dot(X,w) # if it is equal to y , which means w is correct 

array([ 4., -7.])

    in pytorch 

In [51]:
X = pt.tensor([[4,2],[-5,-3.]])
X

tensor([[ 4.,  2.],
        [-5., -3.]])

In [52]:
y = pt.tensor([4,-7.])
y

tensor([ 4., -7.])

In [57]:
pt.inverse(X)

RuntimeError: Calling torch.linalg.lu_factor on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.

in tensorflow 

In [58]:
X = tf.Variable([[4,2],[-5,-3.]])
X

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 4.,  2.],
       [-5., -3.]], dtype=float32)>

In [59]:
y = tf.Variable([4,-7.])
y

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([ 4., -7.], dtype=float32)>

In [61]:
Xinv = tf.linalg.inv(X)
Xinv

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>

In [64]:
w = tf.linalg.matvec(Xinv,y)
w

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.9999995,  3.999999 ], dtype=float32)>