### Transpose of a tensor

In [10]:
import tensorflow as tf
import torch as tr
import numpy as np

In [19]:
tf_X = tf.Variable([[1,2,3],[4,5,6]])

In [20]:
np_X = np.array([[1,2,3],[4,5,6]])

In [32]:
tr_X = tr.tensor([[1,2,3],[4,5,6]])

In [22]:
tf_X

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [23]:
tf.transpose(tf_X)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [24]:
np_X

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np_X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
tr_X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
tr_X.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Basic tensor arithmetic opetations

In [37]:
tf_X*2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [38]:
np_X*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [39]:
tr_X*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [40]:
tf_X+2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]])>

In [41]:
tf_X*2+2 # Python Operators Overloaded 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [10, 12, 14]])>

In [44]:
tf.add(tf.multiply(tf_X,2),2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [10, 12, 14]])>

In [42]:
tr.add(tr.mul(tr_X,2),2)

tensor([[ 4,  6,  8],
        [10, 12, 14]])

### Hadamard product or Element-wise product

In [45]:
np_X

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np_A = np_X + 3
np_A

array([[4, 5, 6],
       [7, 8, 9]])

In [48]:
np_X + np_A 

array([[ 5,  7,  9],
       [11, 13, 15]])

In [49]:
np_X * np_A        # this methord of multiplication called hadamard product or element wise product

array([[ 4, 10, 18],
       [28, 40, 54]])

### Reduction 

######  Calculating the sum of all elements in the tensors

In [50]:
np_X

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.sum(np_X)   # np_X.sum() both are okay

21

In [62]:
np_X.sum(axis = 0)  # summing 1st value in all row , then 2nd value in all row,... like that )

array([5, 7, 9])

In [64]:
np.sum(np_X,1)           #  np_X.sum(axis = 1)

array([ 6, 15])

In [53]:
tf_X

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [56]:
tf.reduce_sum(tf_X)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [58]:
tr.sum(tr_X)

tensor(21)

In [60]:
tf.reduce_sum(tf_X,0) # summing 1st value in all row , then 2nd value in all row,... like that )

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [61]:
tf.reduce_sum(tf_X,1)  # summing 1st value in all column , then 2nd value in all column,... like that )

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 15])>

###  Dot product of Vectors

In [65]:
np_vct_1 = np.array([1,2,3])
np_vct_1

array([1, 2, 3])

In [66]:
np_vct_2 = np.array([5,9,8])
np_vct_2

array([5, 9, 8])

In [67]:
1*5 + 2*9 + 3*8  # Manual way to calculate dot product 

47

In [68]:
np.dot(np_vct_1,np_vct_2)

47

In [71]:
pt_vct_1 = tr.tensor([1,2,3])
pt_vct_1

tensor([1, 2, 3])

In [72]:
pt_vct_2 = tr.tensor([5,9,8])
pt_vct_2

tensor([5, 9, 8])

In [73]:
tr.dot(pt_vct_1,pt_vct_2)

tensor(47)

In [76]:
Y = np.array ([[42,4,7,99],[-99,-3,17,22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [77]:
Y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [78]:
A = np.array([[25,10],[-2,1]])
A

array([[25, 10],
       [-2,  1]])

In [79]:
B = np.array([[-1,7],[10,8]])
B

array([[-1,  7],
       [10,  8]])

In [85]:
A * B

array([[-25,  70],
       [-20,   8]])

In [81]:
k = np.array([-1,2,-2])
k

array([-1,  2, -2])

In [82]:
l = np.array([5,10,0])
l

array([ 5, 10,  0])

In [84]:
np.dot(k,l)

15